#include "arch.h"
#include "fp_GOLDILOCKS.h"

/* Curve GOLDILOCKS */

#if CHUNK==32

const BIG_448 Modulus_GOLDILOCKS= {0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FDFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFF};
const chunk MConst_GOLDILOCKS=0x1;
#endif

#if CHUNK==64
const BIG_448 Modulus_GOLDILOCKS= {0xFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFF,0xFFFEFFFFFFFFFFF,0xFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFF,0xFFFFFFF};
const chunk MConst_GOLDILOCKS=0x1;
#endif


