#include "arch.h"
#include "fp_HIFIVE.h"

/* Curve HIFIVE */

#if CHUNK==32
const BIG_336 Modulus_HIFIVE= {0x1FFFFFFD,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFFFFF,0x1FFFF};
const chunk MConst_HIFIVE=0x3;
#endif

#if CHUNK==64
const BIG_336 Modulus_HIFIVE= {0xFFFFFFFFFFFFFFD,0xFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFF,0xFFFFFFFFFFFFFFF,0xFFFFFFFFF};
const chunk MConst_HIFIVE=0x3;
#endif


